name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: echo Hello, world!
    - name: Run tests
      run: | 
       xcodebuild clean test -project GOMS-iOS.xcodeproj \
        -scheme GOMS-iOS \
        -destination 'platform=iOS Simulator,name=iPhone 13,OS=15.5'
