name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest
    
    env: 
      DECRYPTED_PROVISION_FILE_PATH: ${{ '.github/distribution.cer' }}
      ENCRYPTED_PROVISION_FILE_PATH: ${{ '.github/distribution.cer.gpg' }}
      PROVISION_ENCRYPTION_PWD: ${{ secrets.PROVISION_ENCRYPTION_PWD }}     


    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: | 
        xcodebuild build -project GOMS-iOS.xcodeproj
        -scheme GOMS-iOS 
        -destination 'platform=iOS Simulator,name=iPhone 11 Pro,OS=15'
