name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: | 
        pod install --repo-update --clean-install --project-directory=GOMS-iOS/
        xcodebuild clean test -workspace GOMS-iOS/GOMS-iOS.xcworkspace 
        -scheme GOMS-iOS 
        -destination 'platform=iOS Simulator,name=iPhone 11 Pro,OS=15'

